version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - "~/.pg/pg_data/project:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
       - "5432:5432"